output "zone_id" {
  value       = aws_route53_zone.route53_zone.zone_id
  description = "The ID for the Route53 Zone generated by this module, most likely to be used to attach an ELB to a DNS record."
}
